# Cluster
cluster-enabled yes
cluster-config-file nodes.conf
cluster-node-timeout 5000
cluster-require-full-coverage no
cluster-migration-barrier 1

# Keyspace Notifications (E: keyevent, x: expired)
notify-keyspace-events Ex

# Memory
maxmemory 400mb
maxmemory-policy allkeys-lru

# Persistence (로컬 개발 전용 - AOF/RDB 비활성화)
save ""
appendonly no

# Network
protected-mode no
bind 0.0.0.0
tcp-backlog 511
timeout 0
tcp-keepalive 300

# Logging
loglevel notice
logfile ""
