package com.rocketcrew.pocat.domain.notification.enums;

public enum NotificationType {
    BID_OUTBID,
    AUCTION_WON,
    AUCTION_LOST,
    INSPECTION_PASSED,
    INSPECTION_FAILED,
    SHIPPING,
    SHIPPING_COMPLETED,
    ORDER_CANCELLED,
    SETTLEMENT_CREATED,
    SETTLEMENT_COMPLETED,
    PAYMENT_COMPLETED,
    AUTO_PAYMENT_FAILED,
    DIRECT_PAYMENT_FAILED,
    PAYMENT_FINAL_FAILED,
    REFUND_REQUESTED,
    REFUND_APPROVED,
    REFUND_REJECTED,
    AUCTION_ACTIVATED,
    AUCTION_CANCELLED,
    BID_CREATED
}
