-- V15: 채팅 알림 타입 추가 (채팅방 생성 / 메시지 수신)
ALTER TABLE notifications
    MODIFY COLUMN type ENUM('AUCTION_ACTIVATED','AUCTION_CANCELLED','AUCTION_LOST','AUCTION_SOLD',
                        'AUCTION_WON','AUTO_PAYMENT_FAILED','BID_CREATED','BID_OUTBID',
                        'DIRECT_PAYMENT_FAILED','ESCALATED_PAYMENT_OPPORTUNITY','INSPECTION_FAILED',
                        'INSPECTION_PASSED','ORDER_CANCELLED','PAYMENT_COMPLETED','PAYMENT_FINAL_FAILED',
                        'REFUND_APPROVED','REFUND_REJECTED','REFUND_REQUESTED','SETTLEMENT_COMPLETED',
                        'SETTLEMENT_CREATED','SHIPPING','SHIPPING_COMPLETED',
                        'CHAT_ROOM_CREATED','CHAT_MESSAGE_RECEIVED') NOT NULL;
